using System;
using System.Collections.Generic;

public class Cards
{

    //  Rodzaj karty / Rodzaj znaku / Wartosc karty
    public List<string> AllCards = new List<string>()
    {
        {"2 Serce 2"},
        {"2 Dzwonek 2"},
        {"2 Wino 2"},
        {"2 Żołądź 2"},
        {"3 Serce 3"},
        {"3 Dzwonek 3"},
        {"3 Wino 3"},
        {"3 Żołądź 3"},
        {"4 Serce 4"},
        {"4 Dzwonek 4"},
        {"4 Wino 4"},
        {"4 Żołądź 4"},
        {"5 Serce 5"},
        {"5 Dzwonek 5"},
        {"5 Wino 5"},
        {"5 Żołądź 5"},
        {"6 Serce 6"},
        {"6 Dzwonek 6"},
        {"6 Wino 6"},
        {"6 Żołądź 6"},
        {"7 Serce 7"},
        {"7 Dzwonek 7"},
        {"7 Wino 7"},
        {"7 Żołądź 7"},
        {"8 Serce 8"},
        {"8 Dzwonek 8"},
        {"8 Wino 8"},
        {"8 Żołądź 8"},
        {"9 Serce 9"},
        {"9 Dzwonek 9"},
        {"9 Wino 9"},
        {"9 Żołądź 9"},
        {"10 Serce 10"},
        {"10 Dzwonek 10"},
        {"10 Wino 10"},
        {"10 Żołądź 10"},
        {"J Serce 10"},
        {"J Dzwonek 10"},
        {"J Wino 10"},
        {"J Żołądź 10"},
        {"Q Serce 10"},
        {"Q Dzwonek 10"},
        {"Q Wino 10"},
        {"Q Żołądź 10"},
        {"K Serce 10"},
        {"K Dzwonek 10"},
        {"K Wino 10"},
        {"K Żołądź 10"},
        {"A Serce 1"},
        {"A Dzwonek 1"},
        {"A Wino 1"},
        {"A Żołądź 1"},
    };
}